name: Tear down environments

on:
  pull_request:
    types:
      - closed

jobs:
  clean:
    name: Cleanup Review apps
    runs-on: ubuntu-latest

    steps:
      - name: Get temporary token for invalidating deployment(s)
        id: temp_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.OCTODEMOBOT_APPLICATION_ID_REPO_AUTOMATION }}
          application_private_key: ${{ secrets.OCTODEMOBOT_APPLICATION_KEY_REPO_AUTOMATION }}
          
      - name: Mark environments as inactive in GitHub
        uses: actions/github-script@v2
        with:
          github-token: ${{ steps.temp_token.outputs.token }}
          script: |
            console.log(context.payload.pull_request.head.ref)

            github.repos.listDeployments(
              {
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: context.payload.pull_request.head.ref
              }
            ).then(deployments => {
              const promises = [];

              deployments.data.forEach(deployment => {
                promises.push(github.repos.createDeploymentStatus({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    mediaType: {previews: ["flash-preview", "ant-man"]},
                    deployment_id: deployment.id,
                    state: 'inactive',
                    description: 'Pull Request Merged/Closed, removing review environment'
                  })
                );
              });

              return Promise.all(promises);
            });
